Update updateEnglishLang.yml

diff --git a/.github/workflows/updateEnglishLang.yml b/.github/workflows/updateEnglishLang.yml
--- a/.github/workflows/updateEnglishLang.yml
+++ b/.github/workflows/updateEnglishLang.yml
@@ -9,7 +9,10 @@ on:
         
   repository_dispatch:
     types: [update_english_lang]
-        
+
+permissions:
+  contents: write
+
 jobs:
   updateEnglishLang:
     name: Update English Lang
@@ -46,4 +49,20 @@ jobs:
 
       - name: Update English Lang
         working-directory: ./tools
+        id: update
         run: npx gulp updateEnglishLang
+
+      - name: Commit and Push Lang Changes
+        uses: stefanzweifel/git-auto-commit-action@v5
+        id: commit
+        with:
+          commit_message: ${{ format("Update English Lang Files For Module {0}\n\nNow Up To Date with Commit {1}.", steps.update.module.formattedName, steps.update.link) }}
+          commit_author: nomi-ceu-management[bot] <155502507+nomi-ceu-management[bot]@users.noreply.github.com>
+          commit_user_name: nomi-ceu-management[bot]
+          commit_user_email: 155502507+nomi-ceu-management[bot]@users.noreply.github.com
+
+      - name: Throw Error if No Changes were Detected
+        if: ${{ steps.commit.outputs.changes_detected == 'false' }}
+        run: |
+          echo "No Changes were Detected. Most likely, this is an error."
+          exit 1
